---
- name: Configuration NixOS
  hosts: vps_ovh
  become: yes
  remote_user: ansible
  vars:
    # On lit la clé privée de la machine courante
    my_private_key: "{{ lookup('file', 'keys/' + inventory_hostname + '/private') }}"

  tasks:
    - name: Copier le contenu du dossier nixos dans /etc/nixos
      copy:
        src: ./nixos/
        dest: /etc/nixos/
        owner: root
        group: root
        mode: 0644
        remote_src: no

    - name: Charger les clés publiques en mémoire
      set_fact:
        wireguard_public_key: "{{ lookup('file', 'keys/' + item + '/public') }}"
      delegate_to: localhost
      loop: "{{ groups['vps_ovh'] }}"
      run_once: yes

    - name: Déployer la config Wireguard
      template:
        src: wireguard.nix.j2
        dest: /etc/nixos/wireguard.nix
        owner: root
        mode: "0600" # Contient la clé privée !

    - name: Rebuild
      command: nixos-rebuild switch

    - name: Reconstruire NixOS
      command: nixos-rebuild switch
