- name: Générateur de clés Wireguard
  hosts: all
  connection: local # Tout se passe sur votre PC
  gather_facts: no

  tasks:
    - name: Créer le dossier de clés local
      file:
        path: "keys/{{ inventory_hostname }}"
        state: directory

    - name: Générer Clé Privée (si absente)
      shell: "wg genkey | tee keys/{{ inventory_hostname }}/private"
      args:
        creates: "keys/{{ inventory_hostname }}/private"

    - name: Calculer Clé Publique (à partir de la privée)
      shell: "cat keys/{{ inventory_hostname }}/private | wg pubkey | tee keys/{{ inventory_hostname }}/public"
      # On force la regen de la publique pour être sûr qu'elle matche la privée
