---
#- name: "Phase 1 : Les Secrets"
#  include_tasks: secrets.yml # Il va chercher tasks/secrets.yml

- name: "Phase 2 : Secrets et Wireguard"
  include_tasks: secrets.yml # Il va chercher tasks/wireguard.yml

- name: "Phase 3 : Synchro NixOS"
  synchronize:
    src: "../nixos/" # Là on doit sortir du rôle car le dossier nixos est à la racine
    use_ssh_args: true
    dest: "/etc/nixos/"
    rsync_opts:
      - "--include=modules/***"
      - "--include=profiles/***"
      - "--exclude=*"

- name: "Sync: Pousser la config spécifique du host"
  synchronize:
    src: "../nixos/hosts/{{ inventory_hostname }}/"
    dest: "/etc/nixos/"
    # Optionnel : exclure le hardware-config si vous ne l'avez pas commité
    # rsync_opts:
    #   - "--exclude=hardware-configuration.nix"

- name: "Sync: Pousser la config générale"
  synchronize:
    src: "../config/"
    dest: "/var/lib/config/"
    delete: yes
    recursive: yes

- name: Appliquer la configuration NixOS
  ansible.builtin.command: nixos-rebuild switch
