- name: "SECU: Créer le bunker à secrets"
  file:
    path: /var/lib/secrets
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: "SSH: Vérifier si la clé partagée existe localement"
  delegate_to: localhost
  run_once: true
  become: false
  stat:
    path: "{{ playbook_dir }}/../inventory/group_vars/common_ssh_key"
  register: common_key_stat

- name: "SSH: Générer la clé SSH partagée localement"
  delegate_to: localhost
  run_once: true
  become: false
  command: ssh-keygen -t ed25519 -f "{{ playbook_dir }}/../inventory/group_vars/common_ssh_key" -N "" -C "common-shared-key"
  args:
    creates: "{{ playbook_dir }}/../inventory/group_vars/common_ssh_key.yml"
  when: not common_key_stat.stat.exists

- name: "SSH: Déployer la clé privée partagée"
  copy:
    src: "{{ playbook_dir }}/../inventory/group_vars/common_ssh_key"
    dest: /var/lib/secrets/common-key
    owner: root
    group: root
    mode: "0400"

- name: "Nix: Générer le fichier de variables SSH"
  copy:
    dest: /etc/nixos/ssh-vars.nix # On crée un fichier .nix
    content: |
      {
        certSyncPublicKey = "{{ lookup('file', playbook_dir + '/../inventory/group_vars/common_ssh_key.pub') | trim }}";
      }
    owner: root
    group: root
    mode: "0644" # C'est une clé publique, donc lisible par tous c'est OK

- name: "SECU: Déployer tous les secrets en masse (Python)"
  ansible.builtin.shell: |
    python3 -c '
    import os, json
    secrets = {{ server_secrets | to_json }}
    for filename, content in secrets.items():
        path = f"/var/lib/secrets/{filename}"
        with open(path, "w") as f:
            f.write(content)
        os.chmod(path, 0o400)
        os.chown(path, 0, 0)
    '
  no_log: true

- name: "Wireguard : Déposer la clé privée (Mode sécurisé)"
  copy:
    # On lit la clé locale et on la pousse dans un fichier root-only
    content: "{{ wireguard_private_key }}"
    dest: /var/lib/secrets/wg-private
    owner: root
    group: root
    mode: "0400" # Très strict

- name: "Wireguard : Générer la liste des peers"
  template:
    src: wg-peers.nix.j2
    dest: /etc/nixos/wg-peers.nix
    owner: root
    group: root
    mode: "0644" # Ce fichier contient des IPs et clés publiques, pas grave s'il est lu
