- name: Générateur de clés Wireguard (Version Vault)
  hosts: vps
  connection: local
  gather_facts: no
  become: no

  vars:
    root_dir: "{{ playbook_dir }}/.."
    host_vars_dir: "{{ root_dir }}/inventory/host_vars/{{ inventory_hostname }}"

  tasks:
    - name: Créer le dossier host_vars s'il n'existe pas
      file:
        path: "{{ host_vars_dir }}"
        state: directory

    - name: Vérifier si la clé existe déjà (pour ne pas tout écraser)
      stat:
        path: "{{ host_vars_dir }}/wireguard-secret.yml"
      register: secret_file

    - name: Génération des clés (Uniquement si absent)
      block:
        - name: Générer Clé Privée en mémoire
          shell: "wg genkey"
          register: wg_private_raw

        - name: Calculer Clé Publique en mémoire
          shell: "echo '{{ wg_private_raw.stdout }}' | wg pubkey"
          register: wg_public_raw

        - name: Sauvegarder la clé publique (YAML)
          copy:
            dest: "{{ host_vars_dir }}/wireguard-public.yml"
            content: |
              wireguard_public_key: "{{ wg_public_raw.stdout }}"

        - name: Sauvegarder la clé privée (YAML)
          copy:
            dest: "{{ host_vars_dir }}/wireguard-secret.yml"
            content: |
              wireguard_private_key: "{{ wg_private_raw.stdout }}"

      when: not secret_file.stat.exists
